<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\FastDownload.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="BuildXL.Azurite.Executables" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.BuildXL.Cache.ContentStore.Library" />
    <PackageReference Include="NLog" />
    <PackageReference Include="Shouldly" />

    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(PkgBuildXL_Azurite_Executables)\tools\win-x64\blob.exe" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
