// Copyright (C) Microsoft Corporation. All Rights Reserved.

using System.Diagnostics;
using System.Reflection;

namespace FastDownload.Tests.Utilities
{
    /// <summary>
    /// This converts any exception generated by Debug.Assert style assertions into exceptions. This is useful for
    /// finding tests that trigger assertions. Without this, the test would crash the test process with a cryptic
    /// message.
    ///
    /// See: https://github.com/microsoft/vstest/issues/2309
    /// </summary>
    internal sealed class DebugTraceListener(TraceListener defaultListener) : TraceListener
    {
        public override void Fail(string? message) => Fail(message, null);

        public override void Fail(string? message, string? detailMessage)
        {
            if (detailMessage != null)
            {
                message = $"{message} {detailMessage}";
            }

            var stack = new StackTrace(true);
            var report = GetReport(message, stack);
            WriteLine(report);

            throw new DebugAssertException(report, stack);
        }

        public override void Write(string? message)
        {
            defaultListener.Write(message);
        }

        public override void WriteLine(string? message)
        {
            defaultListener.WriteLine(message);
        }

        private static string GetReport(string message, StackTrace stack)
        {
            var frames = stack.GetFrames();
            string report = null;
            MethodBase debugMethod = null;
            StackFrame frame = null;
            foreach (var f in frames)
            {
                if (debugMethod != null)
                {
                    if (f.HasMethod())
                    {
                        frame = f;
                        break;
                    }
                }

                if (f.HasMethod())
                {
                    var m = f.GetMethod();
                    if (m.DeclaringType == typeof(Debug))
                    {
                        debugMethod = m;
                    }
                }
            }

            if (frame != null)
            {
                if (frame.HasSource())
                {
                    var fileName = frame.GetFileName();
                    var lineNumber = frame.GetFileLineNumber();
                    string line = null;
                    using (var sr = new StreamReader(fileName))
                    {
                        for (int i = 1; i < lineNumber; i++)
                        {
                            sr.ReadLine();
                        }

                        line = sr.ReadLine();
                    }

                    var filteredMessage = message == "Fail:" ? null : message;

                    report += Environment.NewLine;
                    report += Environment.NewLine;

                    if (filteredMessage != null)
                    {
                        report += filteredMessage;
                    }

                    if (line != null)
                    {
                        report = string.Join(Environment.NewLine, "Debug failed at:", line.Trim());
                    }
                }
            }

            return report;
        }

        internal sealed class DebugAssertException : Exception
        {
            public DebugAssertException(string message, StackTrace stack)
                : base(message ?? "Debug.Assert failed.")
            {
                StackTrace = stack.ToString();
            }

            public override string StackTrace { get; }
        }
    }
}
